# Generated by Django 2.2 on 2019-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='имя автора записи')),
                ('mail', models.EmailField(max_length=100, verbose_name='почта автора записи')),
                ('details', models.TextField(max_length=2000, verbose_name='текст записи')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=50, verbose_name='статус')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
        ),
    ]
